matrix:
    include:
        - os: linux
          language: c
          compiler: gcc
          env:
              - MATRIX_EVAL="echo ok"

        - os: linux
          language: c
          compiler: clang
          env:
              - MATRIX_EVAL="sudo apt-get install libiomp-dev"

        - os: osx
          language: c
          compiler: clang
          env:
              - MATRIX_EVAL="brew install libomp"

before install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

sudo: false

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - rm -r ./*
  - if [[ "$MATRIX_EVAL" == "echo ok" ]];
    then cmake .. -DOPENMP=1 -DFORCEIOMP=1; else cmake .. -DOPENMP=1; fi
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - make install

notifications:
  email: false


#language: c

#os:
#  - linux
#  - osx

#compiler:
#  - gcc
#  - clang

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#                                      sudo apt-get install libiomp-dev #--yes; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake  ; fi



