language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - rm build -dr
  - mkdir build
  - cd build
  - cmake .. -DOPENMP=1
  - make

notifications:
  email: false

