language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "clang" ]]; then
                                      sudo apt-get install libiomp-dev --yes; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

sudo: false

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; else sw_vers; fi
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then
                                         gcc --version; else clang --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "gcc" ]]; then
                                     locate libm.so libpthread.so libgomp.so; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "clang" ]]; then
               locate libm.so libpthread.so libiomp.so libiomp5.so libomp.so; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_COMPILER" == "gcc" ]]; then
              locate libm.dylib libpthread.dylib libiomp5.dylib libomp.dylib; fi
  - git --version
  - make --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - rm -r ./*
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "clang" ]]; then
                 cmake .. -DOPENMP=1 -DFORCEIOMP=1; else cmake .. -DOPENMP=1; fi
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - make install

notifications:
  email: false

