matrix:
    include:
        - os: linux
          language: c
          compiler: gcc
          env:
              - INSTALL_COMMAND="sudo ok"
              - FORCEIOMP_FLAG="echo gomp"

        - os: linux
          language: c
          compiler: clang
          env:
              - INSTALL_COMMAND="sudo apt-get install libiomp-dev --yes"
              - FORCEIOMP_FLAG="echo iomp"

        - os: osx
          language: c
          compiler: clang
          env:
              - INSTALL_COMMAND="brew install libomp"
              - FORCEIOMP_FLAG="echo omp"

before install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

sudo: false

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - rm -r ./*
  - if [[ "$FORCEIOMP_FLAG" == "echo iomp" ]];
    then cmake .. -DOPENMP=1 -DFORCEIOMP=1; else cmake .. -DOPENMP=1; fi
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - make install

notifications:
  email: false

