language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

sudo: false

script: 
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - rm -r ./*
  - cmake .. -DOPENMP=1
  - make

notifications:
  email: false

