language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: disabled

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - rm -r ./*
  - cmake .. -DOPENMP=1
  - make

notifications:
  email: false

