language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  - icc

addons:
  apt:
    packages:
      - libpthread-stubs0-dev
      - libgomp1

before_install:
  - if [["$TRAVIS_OS_NAME"=="osx"]]; then brew update                       ; fi
  - if [["$TRAVIS_OS_NAME"=="osx"]]; then brew install libpthread-stubs0-dev; fi
  - if [["$TRAVIS_OS_NAME"=="osx"]]; then brew install libgomp1             ; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DOPENMP=1
  - make

notifications:
  email: false
