language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: disabled

addons:
  apt:
    packages:
      - gcc
      - make
      - cmake
      - git
      - libgomp1
      - libpthread-stubs0-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install clang-omp; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - rm -r ./*
  - cmake .. -DOPENMP=1
  - make

notifications:
  email: false

